name: gestion_recetas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# ----- Packages -----
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  mongo_dart: ^0.9.2
  mailer: ^6.0.0
  google_sign_in: ^5.4.0
  
  # ---- Utility Packages ----
  salomon_bottom_bar: ^3.3.2

  # ---- Icons ----
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # ---- State Management ----
  get: ^4.7.2
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.27
  flutter_native_splash: ^2.4.5
  image_picker: ^0.8.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ---- Local Assets ----
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
          style: normal
