name: gestion_recetas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# ----- Packages -----
dependencies:
  flutter:
    sdk: flutter

  # ---- Utilyity Packpages ----


  # ---- Icons ----
  cupertino_icons: ^1.0.8

  # ---- State Management ----



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  # ---- Local Assets ----
  assets:
    - assets\logos
    - assets\images
    - assets\icons
  fonts:
    - family: Poppins
      fonts:
        - assets: assets\fonts\Poppins-Regular.ttf
          weight: 400
          style: normal
        - assets: assets\fonts\Poppins-Bold.ttf
          weight: 700
          style: normal
        - assets: assets\fonts\Poppins-Italic.ttf
          weight: 400
          style: italic
        - assets: assets\fonts\Poppins-Black.ttf
          weight: 900
          style: normal
          



